geumjue/mongddang

src/app/app.component.html
src/app/app.component.scss

app 전체 가운데 정렬했습니다.

---

package-lock.json
package.json
src/app/app-routing.module.ts
src/app/tab1/tab1.page.html
src/app/tab1/tab1.page.ts

tab1에서 series페이지 연결 commit합니다.

tab1에서 series페이지 연결 commit합니다.

---

src/app/series/series-routing.module.ts
src/app/series/series.module.ts
src/app/series/series.page.html
src/app/series/series.page.scss
src/app/series/series.page.spec.ts
src/app/series/series.page.ts

series페이지 commit합니다

---

src/app/create-account/create-account-routing.module.ts
src/app/create-account/create-account.page.html
src/app/create-account/create-account.page.scss
src/app/create-account/create-account.page.ts
src/app/tab3/tab3.page.html
src/app/tab3/tab3.page.ts

tab3 <->create-account 페이지 이동 기능 commit합니다.

---

src/app/tab1/tab1-routing.module.ts
src/app/tab1/tab1.page.html
src/app/tab1/tab1.page.ts
src/app/tab2/tab2.page.html

tab1 페이지 routing 경로 변경 commit합니다

tab1 페이지 routing 경로 변경 commit합니다

---

src/app/create-account/create-account.page.html
src/app/create-account/create-account.page.scss
src/app/tab3/tab3-routing.module.ts
src/app/tab3/tab3.page.ts

create-account 페이지 css적용

---

src/app/app.component.html
src/app/app.component.scss
src/app/tab1/tab1.page.html
src/app/tab1/tab1.page.scss

scrollbar 수정 commit합니다

---

src/app/app.component.scss
src/app/services/auth.service.ts
src/app/tab3/tab3.page.html
src/app/tab3/tab3.page.scss
src/app/tab3/tab3.page.ts
src/app/tabs/tabs.page.html
src/app/tabs/tabs.page.spec.ts
src/app/tabs/tabs.page.ts

테스트코드지만. 로그인 버튼 누르고 로그아웃시 탭 하단바 개수가 바뀜.

로그인 로그아웃 code 작성

---

src/app/mypage-tab5/mypage-tab5.page.html
src/app/mypage-tab5/mypage-tab5.page.ts
src/app/tab3/tab3.page.html
src/app/tab3/tab3.page.ts
src/app/tabs/tabs.page.html

tab5에 로그아웃btn 생성.

---

src/app/app-routing.module.ts
src/app/tab1/tab1.page.html
src/app/tab1/tab1.page.scss
src/app/tab1/tab1.page.ts

slider commit합니다

---

src/app/tab1/tab1.page.html
src/app/tab1/tab1.page.scss
src/global.scss

comment 부분 commit합니다

---

src/app/mypage-tab5/mypage-tab5.page.html
src/app/mypage-tab5/mypage-tab5.page.scss

프로필만 중앙,
나머지 보관함, 좋아요 타이틀은 왼쪽 정렬했습니다.

마이페이지 카드 타이틀 위치 변경 완료

---

src/app/app-routing.module.ts
src/app/comment/comment-routing.module.ts
src/app/comment/comment.module.ts
src/app/comment/comment.page.html
src/app/comment/comment.page.scss
src/app/comment/comment.page.spec.ts
src/app/comment/comment.page.ts
src/app/tab1/tab1-routing.module.ts
src/app/tab1/tab1.page.html
src/app/tab1/tab1.page.scss
src/app/tab1/tab1.page.ts

comment page 제작 및 routing 연결 commit합니다

comment page 제작 및 routing 연결 commit합니다

---

src/app/tab1/tab1.page.html
src/app/tab1/tab1.page.scss

메인페이지 케빈 이미지에 text추가

---

src/app/app-routing.module.ts
src/app/tab1/tab1-routing.module.ts
src/app/tab1/tab1.page.html
src/app/tab1/tab1.page.scss
src/app/tab1/tab1.page.ts

메인 검색 버튼클릭시 tab2이동 라우팅 구현.
메인페이지 preview(케빈이미지) css 구현.

Kevin text

---

src/app/auth/login/login.page.html
src/app/auth/login/login.page.scss

login 페이지 수정했습니다

---

package-lock.json
src/app/home/home.page.html
src/app/home/home.page.scss
src/app/movie/movie-detail/movie-detail.page.html
src/app/movie/movie-detail/movie-detail.page.scss
src/app/movie/movie-detail/movie-detail.page.ts

modal 추가 및 slider기능 수정했습니다

---

src/app/movie/movie-detail/movie-detail.page.html
src/app/movie/movie-detail/movie-detail.page.scss
src/app/movie/movie-detail/movie-detail.page.ts

modal 기능 수정합니다

---

src/app/app-routing.module.ts
src/app/auth/create-account/create-account.page.html
src/app/collection/collection-routing.module.ts
src/app/collection/collection.page.html
src/app/collection/collection.page.scss
src/app/collection/collection.page.ts
src/app/collection/upload-collection/upload-collection-routing.module.ts
src/app/collection/upload-collection/upload-collection.module.ts
src/app/collection/upload-collection/upload-collection.page.html
src/app/collection/upload-collection/upload-collection.page.scss
src/app/collection/upload-collection/upload-collection.page.spec.ts
src/app/collection/upload-collection/upload-collection.page.ts

Collection item

---

src/app/models/movie/movie-getmovie-response-data.interface.ts
src/app/models/movie/movie-getmoviebyid-response-data.interface.ts
src/app/pages/home/home.page.html
src/app/pages/home/home.page.ts
src/app/pages/movie/movie-detail/movie-detail.page.html
src/app/pages/movie/movie-detail/movie-detail.page.ts
src/app/services/movie/movie.service.ts

- 영화 목록 조회해서 슬라이더에 넣기
- 영화 정보 조회해서 상세 페이지 변경
- 댓글 목록 조회 연동

영화 목록 조회, 정보 조회 API 연동 완료했습니다.

---

src/app/pages/movie/movie-detail/movie-detail.page.html
src/app/pages/movie/movie-detail/movie-detail.page.ts

정보 조회 API 연동 완료했습니다.

---

src/app/pages/movie/movie-comment/comment-write/comment-write.page.html
src/app/pages/movie/movie-comment/comment-write/comment-write.page.ts
src/app/pages/movie/movie-routing.module.ts
src/app/services/commet/comment.sevice.ts

comment 충돌 부분 에러 수정합니다.

---

src/app/pages/movie/movie-detail/movie-detail.page.ts
src/app/services/auth/auth.service.ts

충돌 오류 해결합니다.

---

src/app/pages/auth/login/login.page.ts
src/app/pages/auth/mypage/mypage.page.html
src/app/pages/auth/mypage/mypage.page.ts
src/app/services/auth/auth.service.ts

충돌 오류 해결하는 중입니다

---

src/app/pages/auth/login/login.page.ts
src/app/pages/auth/mypage/mypage.page.ts
src/app/services/auth/auth.service.ts

경로 추가 및 오류 수정

---

src/app/models/auth/auth-reponse.interface.ts
src/app/pages/auth/login/login.page.html
src/app/pages/auth/login/login.page.ts
src/app/pages/auth/mypage/mypage.page.ts
src/app/services/auth/auth.service.ts
src/app/services/user/user.service.ts

Login error

---

package-lock.json
package.json
src/app/pages/movie/movie-detail/movie-detail.page.html
src/app/pages/movie/movie-detail/movie-detail.page.ts

컬렉션 추가 : 모달 기능 추가합니다

---

src/app/models/auth/auth-reponse.interface.ts
src/app/models/collection/collection-getcollections.interface.data.ts
src/app/models/collection/collection-postcollection.interface.data.ts
src/app/models/collection/collection-updatecollection.interface.data.ts
src/app/pages/movie/movie-detail/movie-detail.page.html
src/app/pages/movie/movie-detail/movie-detail.page.ts
src/app/services/auth/auth.service.ts
src/app/services/collection/collection.service.ts

컬렉션 api 요청합니다.

---

src/app/app-routing.module.ts
src/app/pages/home/home.page.html
src/app/pages/home/home.page.ts
src/app/pages/movie/movie-comment/comment-list/comment-list.page.html
src/app/pages/movie/movie-comment/comment-list/comment-list.page.scss
src/app/pages/movie/movie-comment/comment-list/comment-list.page.ts
src/app/pages/movie/movie-detail/movie-detail.page.html
src/app/pages/movie/movie-detail/movie-detail.page.scss
src/app/pages/movie/movie-detail/movie-detail.page.ts
src/app/pages/movie/movie-routing.module.ts
src/app/pages/movie/movie.module.ts

collection-list 페이지 생성 및 nows-comment라우팅 연결

collection-list 페이지 생성 및 nows-comment라우팅 연결합니다

---

src/app/pages/auth/mypage/mypage.page.html
src/app/pages/auth/mypage/mypage.page.scss
src/app/pages/collection/upload-collection/upload-collection.page.html
src/app/pages/home/home.page.html
src/app/pages/home/home.page.scss
src/app/pages/home/nows-comment/nows-comment.page.html
src/app/pages/home/nows-comment/nows-comment.page.ts
src/app/pages/movie/movie-detail/movie-detail.page.html
src/app/pages/movie/movie-detail/movie-detail.page.scss
src/app/pages/movie/movie-detail/movie-detail.page.ts
src/app/pages/movie/movie-search/search.page.html
src/app/pages/movie/movie-search/search.page.ts

홈 / 영화상세정보/ 지금뜨는 코멘트 / 검색 페이지 css 수정

---

src/app/pages/movie/movie-comment/comment-list/comment-list.page.html
src/app/pages/movie/movie-comment/comment-list/comment-list.page.scss
src/app/pages/movie/movie-detail/movie-detail.page.html

collection-list 및  movie-detail 부분 comment-list 수정

collection-list 및  movie-detail 부분 comment-list 수정합니다

---

src/app/pages/collection/collection-routing.module.ts
src/app/pages/collection/collection.module.ts
src/app/pages/collection/detail-collection/detail-collection.page.html
src/app/pages/collection/detail-collection/detail-collection.page.scss
src/app/pages/collection/detail-collection/detail-collection.page.ts
src/app/pages/collection/listing-collection/collection.page.html
src/app/pages/collection/listing-collection/collection.page.ts

detail-collection 페이지 추가합니다

---

src/app/pages/auth/mypage/liked-movie/liked-movie.page.html
src/app/pages/auth/mypage/liked-movie/liked-movie.page.scss
src/app/pages/auth/mypage/liked-movie/liked-movie.page.ts
src/app/pages/auth/mypage/mypage.module.ts
src/app/services/favorite/favorite.service.ts

좋아요 기능 1차 구현

---

src/app/app-routing.module.ts
src/app/pages/auth/auth-routing.module.ts
src/app/pages/auth/mypage/my-collection/my-collection.page.html
src/app/pages/auth/mypage/my-collection/my-collection.page.scss
src/app/pages/auth/mypage/mypage-routing.module.ts
src/app/pages/auth/mypage/mypage.module.ts
src/app/pages/auth/mypage/mypage.page.html
src/app/pages/auth/mypage/mypage.page.ts

my-collection 페이지 라우팅 연결

---

src/app/pages/movie/movie-comment/comment-write/comment-write.page.html
src/app/pages/movie/movie-comment/comment-write/comment-write.page.ts

코멘트 작성 후 전체 코멘트 페이지로 이동

---

src/app/app.component.ts
src/app/app.module.ts
src/app/models/auth/auth-reponse.interface.ts
src/app/models/auth/auth-signup-request-data.interface.ts
src/app/models/favorite/checkfavorite-response.data.ts
src/app/models/favorite/favorite-request.data.ts
src/app/models/favorite/favorite-response.data.ts
src/app/models/user/user-getuser-liked-movie-response.data.interface.ts
src/app/pages/auth/create-account/create-account.page.ts
src/app/pages/auth/mypage/liked-movie/liked-movie.page.html
src/app/pages/auth/mypage/liked-movie/liked-movie.page.scss
src/app/pages/auth/mypage/liked-movie/liked-movie.page.ts
src/app/pages/home/home.page.ts
src/app/pages/movie/movie-detail/movie-detail.page.ts
src/app/services/auth/auth.interceptor.ts
src/app/services/auth/auth.service.ts
src/app/services/favorite/favorite.service.ts
src/app/services/user/user.service.ts

영화 좋아요 기능 수정-> 사용자 정보에 따른 좋아요 적용 되도록

영화 좋아요 기능 수정-> 사용자 정보에 따른 좋아요 적용 되도록

---

src/app/pages/movie/movie-comment/comment-write/comment-write.page.html
src/app/pages/movie/movie-comment/comment-write/comment-write.page.scss
src/app/pages/movie/movie-detail/movie-detail.page.html

comment-write 페이지 수정 및 movie-detail 갤러리, 동영상 삭제

comment-write 페이지 수정 및 movie-detail 갤러리, 동영상 삭제

---

package-lock.json
package.json
src/app/app-routing.module.ts
src/app/pages/auth/mypage/my-collection/my-collection.page.html
src/app/pages/auth/mypage/my-collection/my-collection.page.scss
src/app/pages/auth/mypage/my-collection/my-collection.page.ts
src/app/pages/auth/mypage/mypage.page.html
src/app/pages/movie/collection-add/collection-add-routing.module.ts
src/app/pages/movie/collection-add/collection-add.module.ts
src/app/pages/movie/collection-add/collection-add.page.html
src/app/pages/movie/collection-add/collection-add.page.scss
src/app/pages/movie/collection-add/collection-add.page.spec.ts
src/app/pages/movie/collection-add/collection-add.page.ts
src/app/pages/movie/movie-detail/movie-detail.page.html
src/app/pages/movie/movie-detail/movie-detail.page.ts
src/app/pages/movie/movie-routing.module.ts
src/app/services/collection/collection.service.ts

컬렉션에 추가하기 기능 추가

---

src/app/models/comment/comment-list-response-data.ts
src/app/pages/movie/movie-comment/comment-list/comment-list.page.html
src/app/pages/movie/movie-comment/comment-list/comment-list.page.ts
src/app/pages/movie/movie-comment/comment-write/comment-write.page.ts
src/app/services/comment/comment.sevice.ts

comment-list.page에 코멘트 누적 및 최신순 업로드

comment-list.page에 코멘트 누적 및 최신순 업로드

---

src/app/pages/movie/movie-comment/comment-list/comment-list.page.html
src/app/pages/movie/movie-comment/comment-list/comment-list.page.scss
src/app/pages/movie/movie-comment/comment-list/comment-list.page.ts
src/app/pages/movie/movie-detail/movie-detail.page.html
src/app/pages/movie/movie-detail/movie-detail.page.scss

comment-list 페이지 및 movie-detail scss 수정

comment-list 페이지 및 movie-detail scss 수정

---

src/app/pages/home/home.page.html
src/app/pages/home/home.page.scss

home.page에 swiper 및 css 수정

---

src/app/pages/auth/mypage/liked-movie/liked-movie.page.html
src/app/pages/auth/mypage/liked-movie/liked-movie.page.scss
src/app/pages/auth/mypage/liked-movie/liked-movie.page.ts

liked-comment css 수정

---

src/app/pages/auth/mypage/liked-movie/liked-movie.page.html
src/app/pages/auth/mypage/liked-movie/liked-movie.page.scss
src/app/pages/auth/mypage/liked-movie/liked-movie.page.ts

liked-movie css 수정

---

src/app/pages/auth/mypage/mypage.page.ts
src/app/pages/home/home.page.html
src/app/pages/home/home.page.ts
src/app/pages/home/recommendation/recommendation.page.html
src/app/pages/movie/collection-add/collection-add.page.html
src/app/pages/movie/collection-add/collection-add.page.scss

collection-add 수정,  home swiper 장르별로 넣었지만 에러 발생 및 맞춤형 페이지 이동

collection-add 수정,  home swiper 장르별로 넣었지만 에러 발생 및 맞춤형 페이지 이동

---

src/app/app.component.scss
src/app/pages/home/recommendation/recommendation.page.html
src/app/pages/home/recommendation/recommendation.page.scss
src/global.scss

recommendation.page 수정 및 app.component page 가운데 정렬

recommendation.page 수정 및 app.component page 가운데 정렬
